package com.balancedbytes.games.ffb.client;

import com.balancedbytes.games.ffb.SkillCategory;
import com.balancedbytes.games.ffb.model.Skill;

public class ClientSkillConstants {
  public static final Skill ACCURATE = new Skill("Accurate", SkillCategory.PASSING);
  public static final Skill ALWAYS_HUNGRY = new Skill("Always Hungry", SkillCategory.EXTRAORDINARY);
  public static final Skill ANIMOSITY = new Skill("Animosity", SkillCategory.EXTRAORDINARY);
  public static final Skill BALL_AND_CHAIN = new Skill("Ball and Chain", SkillCategory.EXTRAORDINARY);
  public static final Skill BIG_HAND = new Skill("Big Hand", SkillCategory.MUTATION);
  public static final Skill BLOCK = new Skill("Block", SkillCategory.GENERAL);
  public static final Skill BLOOD_LUST = new Skill("Blood Lust", SkillCategory.EXTRAORDINARY);
  public static final Skill BOMBARDIER = new Skill("Bombardier", SkillCategory.EXTRAORDINARY);
  public static final Skill BONE_HEAD = new Skill("Bone-Head", SkillCategory.EXTRAORDINARY);
  public static final Skill BREAK_TACKLE = new Skill("Break Tackle", SkillCategory.STRENGTH);
  public static final Skill CATCH = new Skill("Catch", SkillCategory.AGILITY);
  public static final Skill CHAINSAW = new Skill("Chainsaw", SkillCategory.EXTRAORDINARY);
  public static final Skill CLAW = new Skill("Claw", SkillCategory.MUTATION);
  public static final Skill DAUNTLESS = new Skill("Dauntless", SkillCategory.GENERAL);
  public static final Skill DECAY = new Skill("Decay", SkillCategory.EXTRAORDINARY);
  public static final Skill DIRTY_PLAYER = new Skill("Dirty Player", SkillCategory.GENERAL);
  public static final Skill DISTURBING_PRESENCE = new Skill("Disturbing Presence", SkillCategory.MUTATION);
  public static final Skill DIVING_CATCH = new Skill("Diving Catch", SkillCategory.AGILITY);
  public static final Skill DIVING_TACKLE = new Skill("Diving Tackle", SkillCategory.AGILITY);
  public static final Skill DISPOSABLE = new Skill("Disposable", SkillCategory.EXTRAORDINARY);
  public static final Skill DODGE = new Skill("Dodge", SkillCategory.AGILITY);
  public static final Skill DUMP_OFF = new Skill("Dump-Off", SkillCategory.PASSING);
  public static final Skill EXTRA_ARMS = new Skill("Extra Arms", SkillCategory.MUTATION);
  public static final Skill FAN_FAVOURITE = new Skill("Fan Favourite", SkillCategory.EXTRAORDINARY);
  public static final Skill FEND = new Skill("Fend", SkillCategory.GENERAL);
  public static final Skill FOUL_APPEARANCE = new Skill("Foul Appearance", SkillCategory.MUTATION);
  public static final Skill FRENZY = new Skill("Frenzy", SkillCategory.GENERAL);
  public static final Skill GRAB = new Skill("Grab", SkillCategory.STRENGTH);
  public static final Skill GUARD = new Skill("Guard", SkillCategory.STRENGTH);
  public static final Skill HAIL_MARY_PASS = new Skill("Hail Mary Pass", SkillCategory.PASSING);
  public static final Skill HORNS = new Skill("Horns", SkillCategory.MUTATION);
  public static final Skill HYPNOTIC_GAZE = new Skill("Hypnotic Gaze", SkillCategory.EXTRAORDINARY);
  public static final Skill JUGGERNAUT = new Skill("Juggernaut", SkillCategory.STRENGTH);
  public static final Skill JUMP_UP = new Skill("Jump Up", SkillCategory.AGILITY);
  public static final Skill KICK = new Skill("Kick", SkillCategory.GENERAL);
  public static final Skill KICK_OFF_RETURN = new Skill("Kick-Off Return", SkillCategory.GENERAL);
  public static final Skill KICK_TEAM_MATE = new Skill("Kick Team-Mate", SkillCategory.EXTRAORDINARY);
  public static final Skill LEADER = new Skill("Leader", SkillCategory.PASSING);
  public static final Skill LEAP = new Skill("Leap", SkillCategory.AGILITY);
  public static final Skill LONER = new Skill("Loner", SkillCategory.EXTRAORDINARY);
  public static final Skill MIGHTY_BLOW = new Skill("Mighty Blow", SkillCategory.STRENGTH);
  public static final Skill MOUNSTROUS_MOUTH = new Skill("Monstrous Mouth", SkillCategory.EXTRAORDINARY);
  public static final Skill MULTIPLE_BLOCK = new Skill("Multiple Block", SkillCategory.STRENGTH);
  public static final Skill NERVES_OF_STEEL = new Skill("Nerves of Steel", SkillCategory.PASSING);
  public static final Skill NO_HANDS = new Skill("No Hands", SkillCategory.EXTRAORDINARY);
  public static final Skill NURGLES_ROT = new Skill("Nurgle's Rot", SkillCategory.EXTRAORDINARY);
  public static final Skill PASS = new Skill("Pass", SkillCategory.PASSING);
  public static final Skill PASS_BLOCK = new Skill("Pass Block", SkillCategory.GENERAL);
  public static final Skill PILING_ON = new Skill("Piling On", SkillCategory.STRENGTH);
  public static final Skill PREHENSILE_TAIL = new Skill("Prehensile Tail", SkillCategory.MUTATION);
  public static final Skill PRO = new Skill("Pro", SkillCategory.GENERAL);
  public static final Skill REALLY_STUPID = new Skill("Really Stupid", SkillCategory.EXTRAORDINARY);
  public static final Skill REGENERATION = new Skill("Regeneration", SkillCategory.EXTRAORDINARY);
  public static final Skill RIGHT_STUFF = new Skill("Right Stuff", SkillCategory.EXTRAORDINARY);
  public static final Skill SAFE_THROW = new Skill("Safe Throw", SkillCategory.PASSING);
  public static final Skill SECRET_WEAPON = new Skill("Secret Weapon", SkillCategory.EXTRAORDINARY);
  public static final Skill SHADOWING = new Skill("Shadowing", SkillCategory.GENERAL);
  public static final Skill SIDE_STEP = new Skill("Side Step", SkillCategory.AGILITY);
  public static final Skill SNEAKY_GIT = new Skill("Sneaky Git", SkillCategory.AGILITY);
  public static final Skill SPRINT = new Skill("Sprint", SkillCategory.AGILITY);
  public static final Skill STAB = new Skill("Stab", SkillCategory.EXTRAORDINARY);
  public static final Skill STAKES = new Skill("Stakes", SkillCategory.EXTRAORDINARY);
  public static final Skill STAND_FIRM = new Skill("Stand Firm", SkillCategory.STRENGTH);
  public static final Skill STRIP_BALL = new Skill("Strip Ball", SkillCategory.GENERAL);
  public static final Skill STRONG_ARM = new Skill("Strong Arm", SkillCategory.STRENGTH);
  public static final Skill STUNTY = new Skill("Stunty", SkillCategory.EXTRAORDINARY);
  public static final Skill SURE_FEET = new Skill("Sure Feet", SkillCategory.AGILITY);
  public static final Skill SURE_HANDS = new Skill("Sure Hands", SkillCategory.GENERAL);
  public static final Skill SWARMING = new Skill("Swarming", SkillCategory.EXTRAORDINARY);
  public static final Skill SWOOP = new Skill("Swoop", SkillCategory.EXTRAORDINARY);
  public static final Skill TACKLE = new Skill("Tackle", SkillCategory.GENERAL);
  public static final Skill TAKE_ROOT = new Skill("Take Root", SkillCategory.EXTRAORDINARY);
  public static final Skill TENTACLES = new Skill("Tentacles", SkillCategory.MUTATION);
  public static final Skill THICK_SKULL = new Skill("Thick Skull", SkillCategory.STRENGTH);
  public static final Skill THROW_TEAM_MATE = new Skill("Throw Team-Mate", SkillCategory.EXTRAORDINARY);
  public static final Skill TIMMMBER = new Skill("Timmm-ber!", SkillCategory.EXTRAORDINARY);
  public static final Skill TITCHY = new Skill("Titchy", SkillCategory.EXTRAORDINARY);
  public static final Skill TWO_HEADS = new Skill("Two Heads", SkillCategory.MUTATION);
  public static final Skill VERY_LONG_LEGS = new Skill("Very Long Legs", SkillCategory.MUTATION);
  public static final Skill WEEPING_DAGGER = new Skill("Weeping Dagger", SkillCategory.EXTRAORDINARY);
  public static final Skill WILD_ANIMAL = new Skill("Wild Animal", SkillCategory.EXTRAORDINARY);
  public static final Skill WRESTLE = new Skill("Wrestle", SkillCategory.GENERAL);
  public static final Skill MOVEMENT_INCREASE = new Skill("+MA", SkillCategory.STAT_INCREASE);
  public static final Skill MOVEMENT_DECREASE = new Skill("-MA", SkillCategory.STAT_DECREASE);
  public static final Skill STRENGTH_INCREASE = new Skill("+ST", SkillCategory.STAT_INCREASE);
  public static final Skill STRENGTH_DECREASE = new Skill("-ST", SkillCategory.STAT_DECREASE);
  public static final Skill AGILITY_INCREASE = new Skill("+AG", SkillCategory.STAT_INCREASE);
  public static final Skill AGILITY_DECREASE = new Skill("-AG", SkillCategory.STAT_DECREASE);
  public static final Skill ARMOUR_INCREASE = new Skill("+AV", SkillCategory.STAT_INCREASE);
  public static final Skill ARMOUR_DECREASE = new Skill("-AV", SkillCategory.STAT_DECREASE);
  
  public ClientSkillConstants() {
  }

}
