package com.fumbbl.ffb.inducement;

import java.util.HashSet;
import java.util.Set;

public enum Usage {
	ADD_LINEMEN, ADD_CHEERLEADER, ADD_COACH, ADD_TO_ARGUE_ROLL, ADD_TO_KO_RECOVERY, APOTHECARY,
	APOTHECARY_JOURNEYMEN, AVOID_BAN, BUGMAN, CHANGE_WEATHER, CONDITIONAL_REROLL, GAME_MODIFICATION, KNOCKOUT_RECOVERY,
	LONER, REGENERATION, REROLL, REROLL_ARGUE, REROLL_CHEERING_FANS, REROLL_ONES_ON_KOS, RESETUP_D3_PLAYERS,
	SPELL, SPOT_FOUL, STAFF, STAR, STEAL_REROLL, THROW_ROCK, UNSPECIFIC;

	public static final Set<Usage> EXCLUDE_FROM_RESULT = new HashSet<Usage>() {{
		add(LONER);
		add(STAR);
		add(STAFF);
		add(REROLL_ARGUE);
		add(REROLL_ONES_ON_KOS);
		add(ADD_TO_KO_RECOVERY);
		add(RESETUP_D3_PLAYERS);
	}};

	public static final Set<Usage> EXCLUDE_FROM_COUNT = new HashSet<Usage>() {{
		add(REROLL_ARGUE);
		add(REROLL_ONES_ON_KOS);
		add(THROW_ROCK);
		add(ADD_TO_KO_RECOVERY);
		add(RESETUP_D3_PLAYERS);
	}};
}
