//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.21 at 05:40:44 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://tyrus.java.net/2013/04", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.glassfish.tyrus.core.wsadl.model;
