package com.balancedbytes.games.ffb.model;

import com.balancedbytes.games.ffb.skill.Accurate;
import com.balancedbytes.games.ffb.skill.AgilityDecrease;
import com.balancedbytes.games.ffb.skill.AgilityIncrease;
import com.balancedbytes.games.ffb.skill.AlwaysHungry;
import com.balancedbytes.games.ffb.skill.Animosity;
import com.balancedbytes.games.ffb.skill.ArmourDecrease;
import com.balancedbytes.games.ffb.skill.ArmourIncrease;
import com.balancedbytes.games.ffb.skill.BallAndChain;
import com.balancedbytes.games.ffb.skill.Block;
import com.balancedbytes.games.ffb.skill.BloodLust;
import com.balancedbytes.games.ffb.skill.Bombardier;
import com.balancedbytes.games.ffb.skill.BoneHead;
import com.balancedbytes.games.ffb.skill.BreakTackle;
import com.balancedbytes.games.ffb.skill.Catch;
import com.balancedbytes.games.ffb.skill.Chainsaw;
import com.balancedbytes.games.ffb.skill.Claw;
import com.balancedbytes.games.ffb.skill.Dauntless;
import com.balancedbytes.games.ffb.skill.Decay;
import com.balancedbytes.games.ffb.skill.DirtyPlayer;
import com.balancedbytes.games.ffb.skill.Disposable;
import com.balancedbytes.games.ffb.skill.DisturbingPresence;
import com.balancedbytes.games.ffb.skill.DivingCatch;
import com.balancedbytes.games.ffb.skill.DivingTackle;
import com.balancedbytes.games.ffb.skill.Dodge;
import com.balancedbytes.games.ffb.skill.DumpOff;
import com.balancedbytes.games.ffb.skill.ExtraArms;
import com.balancedbytes.games.ffb.skill.FanFavourite;
import com.balancedbytes.games.ffb.skill.Fend;
import com.balancedbytes.games.ffb.skill.FoulAppearance;
import com.balancedbytes.games.ffb.skill.Frenzy;
import com.balancedbytes.games.ffb.skill.Grab;
import com.balancedbytes.games.ffb.skill.Guard;
import com.balancedbytes.games.ffb.skill.HailMaryPass;
import com.balancedbytes.games.ffb.skill.Horns;
import com.balancedbytes.games.ffb.skill.HypnoticGaze;
import com.balancedbytes.games.ffb.skill.Juggernaut;
import com.balancedbytes.games.ffb.skill.JumpUp;
import com.balancedbytes.games.ffb.skill.Kick;
import com.balancedbytes.games.ffb.skill.KickOffReturn;
import com.balancedbytes.games.ffb.skill.KickTeamMate;
import com.balancedbytes.games.ffb.skill.Leader;
import com.balancedbytes.games.ffb.skill.Leap;
import com.balancedbytes.games.ffb.skill.Loner;
import com.balancedbytes.games.ffb.skill.MightyBlow;
import com.balancedbytes.games.ffb.skill.MonstrousMouth;
import com.balancedbytes.games.ffb.skill.MovementDecrease;
import com.balancedbytes.games.ffb.skill.MovementIncrease;
import com.balancedbytes.games.ffb.skill.MultipleBlock;
import com.balancedbytes.games.ffb.skill.NervesOfSteel;
import com.balancedbytes.games.ffb.skill.NoHands;
import com.balancedbytes.games.ffb.skill.NurglesRot;
import com.balancedbytes.games.ffb.skill.Pass;
import com.balancedbytes.games.ffb.skill.PassBlock;
import com.balancedbytes.games.ffb.skill.PilingOn;
import com.balancedbytes.games.ffb.skill.PrehensileTail;
import com.balancedbytes.games.ffb.skill.Pro;
import com.balancedbytes.games.ffb.skill.ReallyStupid;
import com.balancedbytes.games.ffb.skill.Regeneration;
import com.balancedbytes.games.ffb.skill.RightStuff;
import com.balancedbytes.games.ffb.skill.SafeThrow;
import com.balancedbytes.games.ffb.skill.SecretWeapon;
import com.balancedbytes.games.ffb.skill.Shadowing;
import com.balancedbytes.games.ffb.skill.SideStep;
import com.balancedbytes.games.ffb.skill.SneakyGit;
import com.balancedbytes.games.ffb.skill.Sprint;
import com.balancedbytes.games.ffb.skill.Stab;
import com.balancedbytes.games.ffb.skill.Stakes;
import com.balancedbytes.games.ffb.skill.StandFirm;
import com.balancedbytes.games.ffb.skill.StrengthDecrease;
import com.balancedbytes.games.ffb.skill.StrengthIncrease;
import com.balancedbytes.games.ffb.skill.StripBall;
import com.balancedbytes.games.ffb.skill.StrongArm;
import com.balancedbytes.games.ffb.skill.Stunty;
import com.balancedbytes.games.ffb.skill.SureFeet;
import com.balancedbytes.games.ffb.skill.SureHands;
import com.balancedbytes.games.ffb.skill.Swarming;
import com.balancedbytes.games.ffb.skill.Swoop;
import com.balancedbytes.games.ffb.skill.Tackle;
import com.balancedbytes.games.ffb.skill.TakeRoot;
import com.balancedbytes.games.ffb.skill.Tentacles;
import com.balancedbytes.games.ffb.skill.ThickSkull;
import com.balancedbytes.games.ffb.skill.ThrowTeamMate;
import com.balancedbytes.games.ffb.skill.Timmmber;
import com.balancedbytes.games.ffb.skill.Titchy;
import com.balancedbytes.games.ffb.skill.TwoHeads;
import com.balancedbytes.games.ffb.skill.VeryLongLegs;
import com.balancedbytes.games.ffb.skill.WeepingDagger;
import com.balancedbytes.games.ffb.skill.WildAnimal;
import com.balancedbytes.games.ffb.skill.Wrestle;

public class SkillConstants {
	public static final Skill ACCURATE = new Accurate();
	public static final Skill AGILITY_DECREASE = new AgilityDecrease();
	public static final Skill AGILITY_INCREASE = new AgilityIncrease();
	public static final Skill ALWAYS_HUNGRY = new AlwaysHungry();
	public static final Skill ANIMOSITY = new Animosity();
	public static final Skill ARMOUR_DECREASE = new ArmourDecrease();
	public static final Skill ARMOUR_INCREASE = new ArmourIncrease();
	public static final Skill BALL_AND_CHAIN = new BallAndChain();
	public static final Skill BLOCK = new Block();
	public static final Skill BLOOD_LUST = new BloodLust();
	public static final Skill BOMBARDIER = new Bombardier();
	public static final Skill BONE_HEAD = new BoneHead();
	public static final Skill BREAK_TACKLE = new BreakTackle();
	public static final Skill CATCH = new Catch();
	public static final Skill CHAINSAW = new Chainsaw();
	public static final Skill CLAW = new Claw();
	public static final Skill DAUNTLESS = new Dauntless();
	public static final Skill DECAY = new Decay();
	public static final Skill DIRTY_PLAYER = new DirtyPlayer();
	public static final Skill DISPOSABLE = new Disposable();
	public static final Skill DISTURBING_PRESENCE = new DisturbingPresence();
	public static final Skill DIVING_CATCH = new DivingCatch();
	public static final Skill DIVING_TACKLE = new DivingTackle();
	public static final Skill DODGE = new Dodge();
	public static final Skill DUMP_OFF = new DumpOff();
	public static final Skill EXTRA_ARMS = new ExtraArms();
	public static final Skill FAN_FAVOURITE = new FanFavourite();
	public static final Skill FEND = new Fend();
	public static final Skill FOUL_APPEARANCE = new FoulAppearance();
	public static final Skill FRENZY = new Frenzy();
	public static final Skill GRAB = new Grab();
	public static final Skill GUARD = new Guard();
	public static final Skill HAIL_MARY_PASS = new HailMaryPass();
	public static final Skill HORNS = new Horns();
	public static final Skill HYPNOTIC_GAZE = new HypnoticGaze();
	public static final Skill JUGGERNAUT = new Juggernaut();
	public static final Skill JUMP_UP = new JumpUp();
	public static final Skill KICK = new Kick();
	public static final Skill KICK_OFF_RETURN = new KickOffReturn();
	public static final Skill KICK_TEAM_MATE = new KickTeamMate();
	public static final Skill LEADER = new Leader();
	public static final Skill LEAP = new Leap();
	public static final Skill LONER = new Loner();
	public static final Skill MIGHTY_BLOW = new MightyBlow();
	public static final Skill MONSTROUS_MOUTH = new MonstrousMouth();
	public static final Skill MOVEMENT_DECREASE = new MovementDecrease();
	public static final Skill MOVEMENT_INCREASE = new MovementIncrease();
	public static final Skill MULTIPLE_BLOCK = new MultipleBlock();
	public static final Skill NERVES_OF_STEEL = new NervesOfSteel();
	public static final Skill NO_HANDS = new NoHands();
	public static final Skill NURGLES_ROT = new NurglesRot();
	public static final Skill PASS = new Pass();
	public static final Skill PASS_BLOCK = new PassBlock();
	public static final Skill PILING_ON = new PilingOn();
	public static final Skill PREHENSILE_TAIL = new PrehensileTail();
	public static final Skill PRO = new Pro();
	public static final Skill REALLY_STUPID = new ReallyStupid();
	public static final Skill REGENERATION = new Regeneration();
	public static final Skill RIGHT_STUFF = new RightStuff();
	public static final Skill SAFE_THROW = new SafeThrow();
	public static final Skill SECRET_WEAPON = new SecretWeapon();
	public static final Skill SHADOWING = new Shadowing();
	public static final Skill SIDE_STEP = new SideStep();
	public static final Skill SNEAKY_GIT = new SneakyGit();
	public static final Skill SPRINT = new Sprint();
	public static final Skill STAB = new Stab();
	public static final Skill STAKES = new Stakes();
	public static final Skill STAND_FIRM = new StandFirm();
	public static final Skill STRENGTH_DECREASE = new StrengthDecrease();
	public static final Skill STRENGTH_INCREASE = new StrengthIncrease();
	public static final Skill STRIP_BALL = new StripBall();
	public static final Skill STRONG_ARM = new StrongArm();
	public static final Skill STUNTY = new Stunty();
	public static final Skill SURE_FEET = new SureFeet();
	public static final Skill SURE_HANDS = new SureHands();
	public static final Skill SWARMING = new Swarming();
	public static final Skill SWOOP = new Swoop();
	public static final Skill TACKLE = new Tackle();
	public static final Skill TAKE_ROOT = new TakeRoot();
	public static final Skill TENTACLES = new Tentacles();
	public static final Skill THICKSKULL = new ThickSkull();
	public static final Skill THROW_TEAM_MATE = new ThrowTeamMate();
	public static final Skill TIMMMBER = new Timmmber();
	public static final Skill TITCHY = new Titchy();
	public static final Skill TWO_HEADS = new TwoHeads();
	public static final Skill VERY_LONG_LEGS = new VeryLongLegs();
	public static final Skill WEEPING_DAGGER = new WeepingDagger();
	public static final Skill WILD_ANIMAL = new WildAnimal();
	public static final Skill WRESTLE = new Wrestle();

	public SkillConstants() {
	}

}
