package com.balancedbytes.games.ffb.server;

import com.balancedbytes.games.ffb.model.Skill;
import com.balancedbytes.games.ffb.server.skill.Accurate;
import com.balancedbytes.games.ffb.server.skill.AgilityDecrease;
import com.balancedbytes.games.ffb.server.skill.AgilityIncrease;
import com.balancedbytes.games.ffb.server.skill.AlwaysHungry;
import com.balancedbytes.games.ffb.server.skill.Animosity;
import com.balancedbytes.games.ffb.server.skill.ArmourDecrease;
import com.balancedbytes.games.ffb.server.skill.ArmourIncrease;
import com.balancedbytes.games.ffb.server.skill.BallAndChain;
import com.balancedbytes.games.ffb.server.skill.Block;
import com.balancedbytes.games.ffb.server.skill.BloodLust;
import com.balancedbytes.games.ffb.server.skill.Bombardier;
import com.balancedbytes.games.ffb.server.skill.BoneHead;
import com.balancedbytes.games.ffb.server.skill.BreakTackle;
import com.balancedbytes.games.ffb.server.skill.Catch;
import com.balancedbytes.games.ffb.server.skill.Chainsaw;
import com.balancedbytes.games.ffb.server.skill.Claw;
import com.balancedbytes.games.ffb.server.skill.Dauntless;
import com.balancedbytes.games.ffb.server.skill.Decay;
import com.balancedbytes.games.ffb.server.skill.DirtyPlayer;
import com.balancedbytes.games.ffb.server.skill.Disposable;
import com.balancedbytes.games.ffb.server.skill.DisturbingPresence;
import com.balancedbytes.games.ffb.server.skill.DivingCatch;
import com.balancedbytes.games.ffb.server.skill.DivingTackle;
import com.balancedbytes.games.ffb.server.skill.Dodge;
import com.balancedbytes.games.ffb.server.skill.DumpOff;
import com.balancedbytes.games.ffb.server.skill.ExtraArms;
import com.balancedbytes.games.ffb.server.skill.FanFavourite;
import com.balancedbytes.games.ffb.server.skill.Fend;
import com.balancedbytes.games.ffb.server.skill.FoulAppearance;
import com.balancedbytes.games.ffb.server.skill.Frenzy;
import com.balancedbytes.games.ffb.server.skill.Grab;
import com.balancedbytes.games.ffb.server.skill.Guard;
import com.balancedbytes.games.ffb.server.skill.HailMaryPass;
import com.balancedbytes.games.ffb.server.skill.Horns;
import com.balancedbytes.games.ffb.server.skill.HypnoticGaze;
import com.balancedbytes.games.ffb.server.skill.Juggernaut;
import com.balancedbytes.games.ffb.server.skill.JumpUp;
import com.balancedbytes.games.ffb.server.skill.Kick;
import com.balancedbytes.games.ffb.server.skill.KickOffReturn;
import com.balancedbytes.games.ffb.server.skill.KickTeamMate;
import com.balancedbytes.games.ffb.server.skill.Leader;
import com.balancedbytes.games.ffb.server.skill.Leap;
import com.balancedbytes.games.ffb.server.skill.Loner;
import com.balancedbytes.games.ffb.server.skill.MightyBlow;
import com.balancedbytes.games.ffb.server.skill.MonstrousMouth;
import com.balancedbytes.games.ffb.server.skill.MovementDecrease;
import com.balancedbytes.games.ffb.server.skill.MovementIncrease;
import com.balancedbytes.games.ffb.server.skill.MultipleBlock;
import com.balancedbytes.games.ffb.server.skill.NervesOfSteel;
import com.balancedbytes.games.ffb.server.skill.NoHands;
import com.balancedbytes.games.ffb.server.skill.NurglesRot;
import com.balancedbytes.games.ffb.server.skill.Pass;
import com.balancedbytes.games.ffb.server.skill.PassBlock;
import com.balancedbytes.games.ffb.server.skill.PilingOn;
import com.balancedbytes.games.ffb.server.skill.PrehensileTail;
import com.balancedbytes.games.ffb.server.skill.Pro;
import com.balancedbytes.games.ffb.server.skill.ReallyStupid;
import com.balancedbytes.games.ffb.server.skill.Regeneration;
import com.balancedbytes.games.ffb.server.skill.RightStuff;
import com.balancedbytes.games.ffb.server.skill.SafeThrow;
import com.balancedbytes.games.ffb.server.skill.SecretWeapon;
import com.balancedbytes.games.ffb.server.skill.Shadowing;
import com.balancedbytes.games.ffb.server.skill.SideStep;
import com.balancedbytes.games.ffb.server.skill.SneakyGit;
import com.balancedbytes.games.ffb.server.skill.Sprint;
import com.balancedbytes.games.ffb.server.skill.Stab;
import com.balancedbytes.games.ffb.server.skill.Stakes;
import com.balancedbytes.games.ffb.server.skill.StandFirm;
import com.balancedbytes.games.ffb.server.skill.StrengthDecrease;
import com.balancedbytes.games.ffb.server.skill.StrengthIncrease;
import com.balancedbytes.games.ffb.server.skill.StripBall;
import com.balancedbytes.games.ffb.server.skill.StrongArm;
import com.balancedbytes.games.ffb.server.skill.Stunty;
import com.balancedbytes.games.ffb.server.skill.SureFeet;
import com.balancedbytes.games.ffb.server.skill.SureHands;
import com.balancedbytes.games.ffb.server.skill.Swarming;
import com.balancedbytes.games.ffb.server.skill.Swoop;
import com.balancedbytes.games.ffb.server.skill.Tackle;
import com.balancedbytes.games.ffb.server.skill.TakeRoot;
import com.balancedbytes.games.ffb.server.skill.Tentacles;
import com.balancedbytes.games.ffb.server.skill.ThickSkull;
import com.balancedbytes.games.ffb.server.skill.ThrowTeamMate;
import com.balancedbytes.games.ffb.server.skill.Timmmber;
import com.balancedbytes.games.ffb.server.skill.Titchy;
import com.balancedbytes.games.ffb.server.skill.TwoHeads;
import com.balancedbytes.games.ffb.server.skill.VeryLongLegs;
import com.balancedbytes.games.ffb.server.skill.WeepingDagger;
import com.balancedbytes.games.ffb.server.skill.WildAnimal;
import com.balancedbytes.games.ffb.server.skill.Wrestle;

public class ServerSkillConstants {
  public static final Skill ACCURATE = new Accurate();
  public static final Skill AGILITY_DECREASE = new AgilityDecrease();
  public static final Skill AGILITY_INCREASE = new AgilityIncrease();
  public static final Skill ALWAYS_HUNGRY = new AlwaysHungry();
  public static final Skill ANIMOSITY = new Animosity();
  public static final Skill ARMOUR_DECREASE = new ArmourDecrease();
  public static final Skill ARMOUR_INCREASE = new ArmourIncrease();
  public static final Skill BALL_AND_CHAIN = new BallAndChain();
  public static final Skill BLOCK = new Block();
  public static final Skill BLOOD_LUST = new BloodLust();
  public static final Skill BOMBARDIER = new Bombardier();
  public static final Skill BONE_HEAD = new BoneHead();
  public static final Skill BREAK_TACKLE = new BreakTackle();
  public static final Skill CATCH = new Catch();
  public static final Skill CHAINSAW = new Chainsaw();
  public static final Skill CLAW = new Claw();
  public static final Skill DAUNTLESS = new Dauntless();
  public static final Skill DECAY = new Decay();
  public static final Skill DIRTY_PLAYER = new DirtyPlayer();
  public static final Skill DISPOSABLE = new Disposable();
  public static final Skill DISTURBING_PRESENCE = new DisturbingPresence();
  public static final Skill DIVING_CATCH = new DivingCatch();
  public static final Skill DIVING_TACKLE = new DivingTackle();
  public static final Skill DODGE = new Dodge();
  public static final Skill DUMP_OFF = new DumpOff();
  public static final Skill EXTRA_ARMS = new ExtraArms();
  public static final Skill FAN_FAVOURITE = new FanFavourite();
  public static final Skill FEND = new Fend();
  public static final Skill FOUL_APPEARANCE = new FoulAppearance();
  public static final Skill FRENZY = new Frenzy();
  public static final Skill GRAB = new Grab();
  public static final Skill GUARD = new Guard();
  public static final Skill HAIL_MARY_PASS = new HailMaryPass();
  public static final Skill HORNS = new Horns();
  public static final Skill HYPNOTIC_GAZE = new HypnoticGaze();
  public static final Skill JUGGERNAUT = new Juggernaut();
  public static final Skill JUMP_UP = new JumpUp();
  public static final Skill KICK = new Kick();
  public static final Skill KICK_OFF_RETURN = new KickOffReturn();
  public static final Skill KICK_TEAM_MATE = new KickTeamMate();
  public static final Skill LEADER = new Leader();
  public static final Skill LEAP = new Leap();
  public static final Skill LONER = new Loner();
  public static final Skill MIGHTY_BLOW = new MightyBlow();
  public static final Skill MONSTROUS_MOUTH = new MonstrousMouth();
  public static final Skill MOVEMENT_DECREASE = new MovementDecrease();
  public static final Skill MOVEMENT_INCREASE = new MovementIncrease();
  public static final Skill MULTIPLE_BLOCK = new MultipleBlock();
  public static final Skill NERVES_OF_STEEL = new NervesOfSteel();
  public static final Skill NO_HANDS = new NoHands();
  public static final Skill NURGLES_ROT = new NurglesRot();
  public static final Skill PASS = new Pass();
  public static final Skill PASS_BLOCK = new PassBlock();
  public static final Skill PILING_ON = new PilingOn();
  public static final Skill PREHENSILE_TAIL = new PrehensileTail();
  public static final Skill PRO = new Pro();
  public static final Skill REALLY_STUPID = new ReallyStupid();
  public static final Skill REGENERATION = new Regeneration();
  public static final Skill RIGHT_STUFF = new RightStuff();
  public static final Skill SAFE_THROW = new SafeThrow();
  public static final Skill SECRET_WEAPON = new SecretWeapon();
  public static final Skill SHADOWING = new Shadowing();
  public static final Skill SIDE_STEP = new SideStep();
  public static final Skill SNEAKY_GIT = new SneakyGit();
  public static final Skill SPRINT = new Sprint();
  public static final Skill STAB = new Stab();
  public static final Skill STAKES = new Stakes();
  public static final Skill STAND_FIRM = new StandFirm();
  public static final Skill STRENGTH_DECREASE = new StrengthDecrease();
  public static final Skill STRENGTH_INCREASE = new StrengthIncrease();
  public static final Skill STRIP_BALL = new StripBall();
  public static final Skill STRONG_ARM = new StrongArm();
  public static final Skill STUNTY = new Stunty();
  public static final Skill SURE_FEET = new SureFeet();
  public static final Skill SURE_HANDS = new SureHands();
  public static final Skill SWARMING = new Swarming();
  public static final Skill SWOOP = new Swoop();
  public static final Skill TACKLE = new Tackle();
  public static final Skill TAKE_ROOT = new TakeRoot();
  public static final Skill TENTACLES = new Tentacles();
  public static final Skill THICKSKULL = new ThickSkull();
  public static final Skill THROW_TEAM_MATE = new ThrowTeamMate();
  public static final Skill TIMMMBER = new Timmmber();
  public static final Skill TITCHY = new Titchy();
  public static final Skill TWO_HEADS = new TwoHeads();
  public static final Skill VERY_LONG_LEGS = new VeryLongLegs();
  public static final Skill WEEPING_DAGGER = new WeepingDagger();
  public static final Skill WILD_ANIMAL = new WildAnimal();
  public static final Skill WRESTLE = new Wrestle();

  public ServerSkillConstants() {
  }

}
