package com.fumbbl.ffb.server.db;

/**
 * 
 * @author Kalimar
 */
public enum DbStatementId {

	PASSWORD_FOR_COACH_QUERY, COACHES_INSERT,

	PLAYER_MARKERS_QUERY, PLAYER_MARKERS_DELETE, PLAYER_MARKERS_INSERT,

	TEAM_SETUPS_QUERY_ALL_FOR_A_TEAM, TEAM_SETUPS_QUERY, TEAM_SETUPS_DELETE, TEAM_SETUPS_INSERT,

	GAMES_INFO_INSERT, GAMES_INFO_INSERT_QUERY, GAMES_INFO_UPDATE, GAMES_INFO_DELETE,

	GAMES_SERIALIZED_INSERT, GAMES_SERIALIZED_UPDATE, GAMES_SERIALIZED_DELETE, GAMES_SERIALIZED_QUERY,

	USER_SETTINGS_DELETE, USER_SETTINGS_INSERT, USER_SETTINGS_QUERY,

	GAME_LIST_QUERY_OPEN_GAMES_BY_COACH, ADMIN_LIST_BY_ID_QUERY, ADMIN_LIST_BY_STATUS_QUERY, TEST_GAME_LIST_QUERY

}
