<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.fumbbl.ffb</groupId>
        <artifactId>ffb</artifactId>
        <version>3.4.0</version>
    </parent>

    <artifactId>ffb-statetest</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.fumbbl.ffb</groupId>
            <artifactId>ffb-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fumbbl.ffb</groupId>
            <artifactId>ffb-server</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>${mockito.artifact}</artifactId>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
